{
	site_name: 'Enblog',
	site_description: 'Simple customizable theme for blogging',
	copyright_notice: 'Theme by Cosmo Myzrail Gorynych',
	$title_author_type: 'title',
	title_author: 'Author',
	author_avatar: '/remote/direct_uploads/1498892379_photo_2017-04-03_20-24-00.jpg',
	$author_avatar_type: 'image',
	author_name: 'Cosmo Myzrail Gorynych',
	author_bio: 'A passionate game developer who loves web and making high-quality content',
	title_theming: 'Theming',
	$title_theming_type: 'title',
	dark_theme: false,
	blog_width: '35em',
	accent_color: '#008cbb',
	$accent_color_type: 'colorpicker',
	background_tint_color: '#dfebf2',
	$background_tint_color_type: 'colorpicker',
	background_tint: '51',
	$background_tint_type: 'slider',
	background_image: '/remote/direct_uploads/1498918381_anthony-delanoix-222456.jpg',
	$background_image_type: 'image',
	tile_background: false,
	accented_headers: false,
	headers_font_family: 'Bitter, Georgia, serif',
	body_text_font_family: 'Raleway, Lato, Verdana, sans-serif',
	title_blogging: 'Blogging',
	$title_blogging_type: 'title',
	show_cover_images_on_blog_post_pages: true,
	show_table_of_content: true,
	show_archive_link: true,
	archive_link_text: 'Archive',
	read_more_link_label: 'Read more…',
	comment_service_code: '<!-- Input here your Disqus or Muut commenting code -->\nSet up your commenting system  in global settings of your project.',
	$comment_service_code_type: 'textarea',
	title_widgets: 'Widgets',
	$title_widgets_type: 'title',
	show_author_info_in_posts: true,
	end_of_post_HTML: '',
	$end_of_post_HTML_type: 'textarea',
	left_bottom_HTML: '<a class="twitter-timeline" data-height="300" data-dnt="true" href="https://twitter.com/enduro_js">Tweets by enduro_js</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>',
	$left_bottom_HTML_type: 'textarea',
	right_bottom_HTML: '<h2>Links</h2>\n<ul>\n  <li><a href="https://www.endurojs.com/" target="_blank">Learn more about enduro.js</a></li>\n  <li><a href="https://www.endurojs.com/docs/themes" target="_blank">Quick start</a></li>\n  <li><a href="https://github.com/Gottwik/Enduro" target="_blank">enduro.js community</a></li>\n  <li><a href="https://www.endurojs.com/themes" target="_blank">More themes</a></li>\n</ul>',
	$right_bottom_HTML_type: 'textarea'
}